---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: references.bib
---
# Introduction {#introduction}

Discussions about the importance of sea-level changes and their causes and consequences are common in academic and non-academic spaces. Modern monitoring of sea-level changes using satellite observation and tide gauges provides an increasing influx of information to record and analyze the real-time evolution of this phenomenon [see @Shennan2015research]. However, as pointed by @Shennan2015research, understanding sea-level changes require information beyond modern techniques to identify long trends driving changes in sea level. For example, the study of long-term sea-level changes improves the ability to predict the consequences of a warmer world by comparing with periods with similar conditions such as the Marine Isotope Stage 5e (MIS-5e) (128-118 ka) [@rovere2019world]. Scientists use different techniques and approaches to estimate relative sea-level changes for studies in such timescales (thousands to hundred thousands of years). First, the measurement, dating, and proxy reconstruction of sea-level indicators (SLI) allow researchers to determine the vertical elevation of the past sea level in a specific location and time. Researchers in that area is commonly referred to as 'geology-oriented' or 'field-oriented' [see @Shennan2015research ; @Milne2015] as their work relies on *in situ* observations and measurements. Second, researchers use computational modeling (i.e., modeling community) to simulate global, regional, and local dynamics of drivers of sea-level changes. Combining the techniques used by both communities allows researchers to understand better the dynamics that control sea-level changes at timescales more prolonged than those usually covered by tide gauges or satellite altimetry data.

Even though proxy reconstruction (Sea level indicators) and modeling of sea-level changes address the same problem, there are multiple challenges to integrating their results. First, sea-level indicators (SLI) and models result from two different research communities, so integration in a shared reference frame is required. @Shennan2015research points to some challenges for this integration. For example, the two communities have different (and multiple) definitions of relevant terms as sea level and relative sea level. Second, sea-level indicators (SLI) result from various techniques with different age and relative sea-level (RSL) uncertainties.
For this reason, statistical methods need to be employed to compare SLI with a deterministic model. Ashe et al. (2019) mention integration challenges for SLI data into statistical methods. For example, the non-Gaussian nature of some of its features and the temporal uncertainties of the data. Additionally, multiple authors mentioned the importance of improving the standardization of SLI data to guarantee correct use of data to build, interpret and compare with deterministic models [see @Shennan2015research; @ashe2019statistical; and @hijma2015protocol]. In summary, the different origins and characteristics of sea-level indicators (SLI) and sea-level models difficult data integration.

In that context, this project aims to investigate the relationship between relative sea-level recorded by sea-level indicators (SLI) and the modeled Glacial Isostatic Adjustment (GIA) process. Specific objectives of this project consist of developing tools to extract SLI from a standardized data set and  GIA values from available models and compare them using a random sampling approach for their temporal and RSL parameters. Despite recent efforts for SLI standardization [see @hijma2015protocol; and @rovere2019world] and multiple methods for statistical analysis of SLI [see @ashe2019statistical], there is a knowledge gap on how to integrate results from large databases of sea-level indicators and deterministic physical models in a way that facilitates its management and discussion. The significance of this approach is that it provides sea-level researchers from both SLI and modeling communities tools to explore, integrate, understand and discuss their research results in a way that guarantees better traceability of their data and methods.

There have been increasing efforts within the 'modeling' community' to promote sharing information with other research communities. In this regard, @Milne2015 points to the importance of making model output available for the geology-oriented community ('field community') to stimulate the interaction of sea-level researchers. Sharing research output is a challenge as models are typically hundreds of large files hard to share with other researchers without proper technical infrastructure. However, some recent and continuous efforts show advances to overcome these technical barriers. For example, Prof. W.R Peltier from the University of Toronto regularly publishes updated versions of Ice Sheet Thickness and Paleotopography models [e.g., ICE-5G @peltier2004global] relevant for sea-level modeling. Similarly, @Spada2019 published $Selen^{4}$ an open-source FORTRAN program to model the Glacial Isostatic Adjustment (i.e., one of the drivers of sea-level changes) that allows other researchers to reproduce the models' output in different machines. Other practices in the community include uploading information into data repositories (e.g., Zenodo) or sharing upon request using private servers.

The availability of new standardized SLI data and sea level-models outputs promotes further integration and comparison on bigger scales than previous studies or with new methodologies. Even though the comparison between SLI and models is an established practice since the comparison of sea-level 'observations' (i.e., sea-level indicators) and GIA models to access the quality of the latter published by @clark1978, their integration is not constraint to a single approach and could vary depending on the context and objective of the study. For example, in the errors-in-variables integrated Gaussian processes proposed by @Cahill2015, relative sea-level values from SLI are corrected using GIA values from physical models to estimate rates of sea-level changes. These examples show that integrating SLI and models could serve different purposes. 

This work presents a method for comparing sea-level indicators from a series of Glacial Isostatic Adjustment (GIA) models. The method computes the subtraction between the sea levels indicators and the GIA models that result in a 'residual' ($\varepsilon$) value. This study will present a methodology test using two case studies along the South American coast. The first area corresponds to the Atlantic passive tectonic margin from Brazil to Argentina, and the second the active tectonic margin from Ecuador to Chile. The study's central hypothesis is that residual values are higher along the active tectonic Pacific coast than the passive Atlantic coast margin. An additional hypothesis is that mean residual values from different sub-regions in these margins vary due to regional geological characteristics. This work compares fitted curves and mean-residual values from each region to test the hypothesis.