---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: references.bib
---

# Discussion {#discussion}

Interpretations of residual values obtained in each case study require individual analysis based on the particular characteristics of the area. This includes the series of assumptions due to the geological characteristics of the regions, the context of the data (GIA models and SLIPs), and the Methodology applied to perform the comparison. Therefore, despite the identical workflow, similar results could have different interpretations (e.g., mean residual values, Kruskal, and Wilcoxon tests).

## South American Atlantic coast 

For the South American Atlantic coast case study, the most important assumptions are that 1) relative sea-level change in this region due to tectonic activity is negligible, and 2) GIA is the main driver of changes in relative sea level. In consequence, the contribution of some of the components that affect the changes on relative sea-level changes could be considered equal to zero. That results in the following relationships derived from Equations \@ref(eq:rsl-process) and 
\@ref(eq:isogiafingerprint):

\begin{equation}
\begin{split}
\Delta RSL(\varphi,t) = \Delta EUS(t) +\Delta ISO_{GIA}(\varphi,t) +\Delta ISO_{fingerprint}(\varphi,t) + \cancel{\Delta TECT(\varphi,t)} \\
+ \cancel{\Delta LOCAL(\varphi,t)} + \cancel{\Delta UNSP(\varphi,t)}
\end{split}
\end{equation}
(\#eq:rsl-atlantic)
\begin{equation}
\varepsilon = \Delta RSL(\varphi,t) - \Delta ISO_{GIA}(\varphi,t)
\end{equation}
(\#eq:epsilon-atlantic-rsl)

Under these assumptions, the Residual ($\varepsilon$) that results from the comparison of SLIPs (Point cloud) and GIA models in the South American Atlantic coast is equal to the sum of the (unknown) Eustatic ($\Delta EUS(t)$) and fingerprint ($\Delta ISO_{fingerprint}(\varphi,t)$) component. 

\begin{equation}
\varepsilon = \Delta EUS(t) + \Delta ISO_{fingerprint}(\varphi,t)
\end{equation}
(\#eq:epsilon-atlantic)

As the Eustatic component ($\Delta EUS(t)$) is not spatially dependent, the Residual ($\varepsilon$) values from different regions should be relatively similar for different regions with variations due to the gravitational isostatic effect ($\Delta ISO_{fingerprint}(\varphi,t)$). Results from the *No-peak sampling* and *Peak sampling* methods for the four regions along the South American Atlantic coast (see Figure \@ref(fig:sa-atlantic-residual-plot)) show that, for periods where all regions have information (e.g., *No-peak sampling* at 130 to 70 ka), the residual values follow a similar trend with small variations. That may suggest that the assumption that the tectonic ($\Delta TECT(\varphi,t)$), local ($\Delta LOCAL(\varphi,t)$), and Unspecified ($\Delta UNSP(\varphi,t)$) effects are negligible is correct. This similar trend is also possible if the net effect of $\Delta TECT(\varphi,t)$, $\Delta LOCAL$, and $\Delta UNSP$ is not zero but equal for all regions. However, the latter scenario is improbable due to the geographical extent of the study. Under the assumption that these components are zero, the fingerprint ($\Delta ISO_{fingerprint}(\varphi,t)$) should be able to explain the variations on residual values. Although the fingerprint is not known for this study, the $\Delta ISO_{fingerprint}(\varphi,t)$ is sensitive to the distance of the melting ice sheet [see @Hay2014], which in this case study varies from the Brazilian northeast to the Argentinian southeast coast and could potentially explain differences in the residuals. 

The notion that all regions share a common trend with variations due to the $\Delta ISO_{fingerprint}(\varphi,t)$ might be contradictory to the results from the Kruskal and Wilcoxon tests (see Table \@ref(tab:sa-atlantic-kruskal) and Table \@ref(tab:sa-atlantic-wilcox-table)) which suggest that all regions have different mean residual values. Although these differences by region are evident (see Figure \@ref(fig:south-america-atlantic-mean-region)), their explanation might not be due to geological reasons but to the context of the data analyzed in each region. While the Brazilian northeast coast only has SLIPs (Point cloud) with a high age density around 120 and 100 ka, other regions have a temporal extend (see *No-peak sampling*) from 175 to 80 ka. For the Argentinian southeast coast, the region has the highest residual mean values around 50m but is also the only region with residual values between 175 and 140 ka. For this period, residual values are above 100m, higher than other periods where all sub-regions have values. The difference of having a period recorded only by one region with high residual values drives up the average residual values for the Argentinian southeast coast. That supports the observation that different mean residual values result from the various periods compared and do not necessarily provide information of geologic relevance. Therefore, similar trends between the regions (fitted residual curves) and different mean residual values are compatible. 

Beyond the differences of mean residual values by regions, the Kruskal and Wilcoxon tests suggested significant differences in residual values by GIA model parameters. For some parameters, such as the Lower Mantle viscosity, the number of significantly different pairs suggests that this parameter influences residual values. However, these differences are inconsistent for most model parameters between sampling methods (see Table  \@ref(tab:sa-atlantic-wilcox-table)). As exceptions, the number of significantly different pairs for lithospheric thickness and the specific model show some consistency between sampling methods. In particular, both sampling methods show that differences in the lithospheric thickness result in different residual values.

In contrast, both sampling methods show that no particular model (5 parameter combination) is consistently different from the other models. That observation could be explained as most of the SLIPs (Point cloud) for these regions have data between 140 ka and 0 ka, where GIA models values tend to have minor variations (see Figure \@ref(fig:south-america-atlantic-gia-plot)). However, as mentioned in the Methodology, the Kruskal and Wilcoxon test results must be interpreted with caution as the residual values do not meet the independence assumption. For example, differences in the age range covered by each region's sea-level index points (SLIPs) affect the final mean residual values comparisons.

## South American Pacific coast

As the South American Pacific coast shows active tectonics, the assumptions differ from the Atlantic case study. In particular, for the Pacific coast is no longer valid to assume that the tectonic effect  ($\Delta TECT(\varphi,t)$) is negligible and that the GIA is the principal driver of sea-level changes. Consequently, for the Pacific coast, the following relationships apply:


\begin{equation}
\begin{split}
\Delta RSL(\varphi,t) = \Delta EUS(t) +\Delta ISO_{GIA}(\varphi,t) +\Delta ISO_{fingerprint}(\varphi,t) + {\Delta TECT(\varphi,t)} \\
+ {\Delta LOCAL(\varphi,t)} + {\Delta UNSP(\varphi,t)}
\end{split}
\end{equation}
(\#eq:rsl-pacific)
\begin{equation}
\varepsilon = \Delta RSL(\varphi,t) - \Delta ISO_{GIA}(\varphi,t)
\end{equation}
(\#eq:epsilon-pacific-rsl)
\begin{equation}
\begin{split}
\varepsilon = \Delta EUS(t) + \Delta ISO_{fingerprint}(\varphi,t) + {\Delta TECT(\varphi,t)} \\
+ {\Delta LOCAL(\varphi,t)} + {\Delta UNSP(\varphi,t)}
\end{split}
\end{equation}
(\#eq:epsilon-pacific)

Under these assumptions, it is not expected to have similar residual values for different regions (like the Atlantic region) as more phenomena are involved in sea-level changes. The *No-peak sampling* and *peak sampling*  methods for the four regions along the South American Pacific coast (see Figure \@ref(fig:south-america-pacific-gia-plot)) show similarities and differences with the Pacific area. On the one hand, similar to the Atlantic region, the GIA models show high variability between 200k and 130 ka and low variability between 130 and 0 ka. However, the Ecuadorian and north Peruvian (Ecuador-Peru[n]) region shows a relatively higher variability than the other regions. On the other hand, SLIPs (Point cloud) values are usually higher than in the Atlantic regions. For example, there are SLIPs in the Ecuador-Peru[N] and Chile[C] regions with relative sea-level values higher than 50 m (and up to 200 m). That observation is consistent with the assumption that $\Delta TECT(\varphi,t)$ is not negligible, and observations of tectonic uplifting in the area resulted from other studies with the same data set of SLIPs [see @Freisleben2021].

Despite the differences in SLIPs values, Residual ($\varepsilon$) values from high-density age ranges (see Figure \@ref(fig:sa-pacific-residual-plot)) seem to follow a similar pattern. All regions coincide with a lowest residual value of around 40-50 m at 130 ka, being the Peruvian central and southern area (Peru[C-S]) slightly higher than the other regions. This might suggest that the net effect of the tectonic ($\Delta TECT(\varphi,t)$), local $\Delta LOCAL(\varphi,t)$ and $\Delta UNSP(\varphi,t)$ is similar between the different regions. An additional factor to consider is that local variations within each region are possible. @Freisleben2021 shows that the elevation of marine terraces (i.e., Elevation parameter for Indicative Range calculation) across these four areas and its derived uplift rate is not constant. For example, the Peru[C-S] regions show marine terraces elevations up to 110 m while the median of all regions coincides around 30 m. Significant higher than the median elevation values occur in all regions as the Manta Peninsula (Ecuador-Peru[N] region), San Juan de Marcona (Peru[C-S]), Mejillones Peninsula (Chile[N]) and the Arauco Peninsula (Chile[C]) [see @Freisleben2021]. Although there are differences within each region, the observation that all regions share the same median elevation parameter for their marine terraces could explain why the residual values follow a similar trend.

As for the Atlantic case study, the similarity of trends in the fitted residual values for all Pacific regions seems to contradict the Kruskal and Wilcoxon tests. The northern Chilean coast (Chile[N]) has the highest mean residual value (for *No-peak sampling*) of around 80 m, while the Peruvian central and south coast (Peru[C-S]) have the lowest mean value around 47 m. In this case, the differences in the age range covered by each region play a role. For example, the Peru[C-S] region only has residual data from 130 to 110 ka for the *No-peak sampling* method. Other areas for the same sampling methods cover SLIPs from around 150 to 75 ka. In particular, the lower temporal constraint for the remaining regions varies from 145 ka for Chile [N], 140 ka for Chile[C], and 130 for Ecuador-Peru[N]. That difference in a period with relatively high residual values (more than 100 m) affects the resulting mean residual values.

Regarding the model parameters, the Kruskal and Wilcoxon tests suggest significant differences in residual values due to different model configurations in a consistent way for both sampling methods (see Table \@ref(tab:sa-pacific-wilcox-table) and \@ref(tab:sa-pacific-kruskal)). In this case, the Propagation, Ice, Upper Mantle viscosity, and Lithospheric thickness parameters seem to produce consistently different residual values. The comparisons by a specific model (216 GIA models) for the Pacific region show a high number of statistically significant different pairs. That suggests a higher sensibility in residual values due to the GIA model in the Pacific than the Atlantic region. That observation is consistent with a higher number of SLIPs before 130 ka (e.g., Chile[N] and Chile[C]), where GIA models show a higher variability (see Figure  \@ref(fig:south-america-pacific-gia-plot)). As more SLIPs are temporally located in an age range with higher GIA variability, resulting residual values are more sensitive to GIA models differences.

## Sampling methods

Differences in the results due to sampling methods had been mentioned in the individual results and discussion by regions. However, general observations are valid for any studied region using these different approaches.

The first, and perhaps the most evident, is that more prominent differences between the methods are expected for regions with more SLIPs with uniform temporal constraints. For example, the northeast Brazilian coast (BR[NE]) has a low number of SLIPs with uniform distribution resulting in similar relative sea-level Point clouds (see Figure \@ref(fig:south-america-pacific-gia-plot) and Table \@ref(tab:sa-atlantic-num-slip)) and consequently similar residual values. In the opposite case, high variations between sampling methods are expected for the south Brazilian coast (BR[S]), where most SLIPs have a uniform temporal constraint.

A second observation is that Point clouds for the *Peak sampling* method seem to cluster around local maximum and minimal relative sea-level values from the GIA models. Although this behavior might be expected, it is relevant to reiterate that peak-sampling ranges are not defined using GIA models but a relative sea-level stack based on proxies published by @Spratt2016stack. This effect might be especially relevant in a region where GIA is the predominant sea-level change driver. GIA and relative sea-level peaks would coincide in this particular case, enabling lower residual values. This observation is consistent with the mean values, Kruskal and Wilcoxon tests that show lower Residual values for the *Peak sampling* method.

Third, because of the SLIPs characteristics, *Peak sampling* results in multiple separate portions of information. As residual values are clustered around peaks, high-density age ranges are concentrated around particular periods. Different factors could explain the differences between the sampling methods results. The most important one is that the definition of a high-density age range is arbitrary (<15% of highest density) and might cause erroneously ignoring periods under some conditions. For example, if a specific temporal constraint is dominant because of the number of SLIPs in the region, other age constraints would always fall in the ‘low-density age’ range. That is especially important for the Pacific study, where different SLIPs around the coast share the same temporal constraint from ‘Referencing points’ for up to 600 km [see @Freisleben2021 Methods]. Similarly, because of the clustering around specific age ranges, intermediate values between peaks also fall into the ‘low-density age’ range and thus are ignored for the curve fitting.

The combination of all effects has different results for each area depending on the context of the SLIPs analyzed. For seven out of eight comparisons between sampling techniques, the results seem to be consistent if compared the relative position of mean values by regions (see Figure \@ref(fig:south-america-atlantic-mean-region) and Fig. \@ref(fig:south-america-pacific-mean-region)). However, for the central Chilean coast (Chile[C]) - Fig. \@ref(fig:south-america-pacific-mean-region)) difference in sampling methods show a high variation in mean residual values from being the second higher around 60 m for the *No-peak sampling* to be the smallest (around 40 m) for the *Peak sampling*. As discussed before, drastic changes could be explained by age ranges differences between the two methods for this region. In particular, Age ranges with high residual values (e.g., over 100 m before 130 ka) are ignored for the *Peak sampling* method, while they are included in the *No-peak sampling* method.

Results from the case studies and the comparison between sampling methods allow concluding on the initial research hypothesis of this study. On the one hand, a comparison between the Atlantic and Pacific region fitted residual curves confirm the initial hypothesis that the active Pacific margin has higher residual values than the passive Atlantic margin. Specifically, while the Pacific coast's residual values fluctuate between 30 to 100 m from 125 to 75 ka, the Atlantic passive margin varies from 0 to 50 m for the same period. As discussed before, this difference might indicate the presence of tectonic uplift only for the Pacific coast. On the other hand, a comparison between mean residual values by sub-regions (i.e., along the same coast) shows no information of geologic value. Mean residual values by sub-regions are affected by the temporal coverage of each region. Therefore, differences should not be interpreted as the result of geological processes.