---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2: 
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: references.bib
---

# Conclusions {#conclusions}

Results from the proposed method for comparison allow general observations of both the studied areas and the comparison method. 

First, comparing case studies between active and passive tectonic margins results in the expected behavior. Specifically, the South American Pacific coast, an active tectonic margin, shows higher residual values than the passive tectonic Atlantic coast. This observation results from comparing the fitted residual curves for all sub-regions where the ones located in the Pacific exhibit higher values for coinciding temporal ranges (e.g., Residual values around 125 ka) than the Atlantic areas. However, the results of both case studies suggest that comparison between regions requires analyzing the context of the compared area's data before reaching conclusions, as SLIPs are temporally and spatially irregular. For example, direct comparison using the mean residual values of areas is misleading as differences could result from different temporal covers instead of geological reasons. Even for regions where the spatial distribution of data is uniform (e.g., Pacific coast), other factors as the age correlation methods used to produce the SLIPs influence the resulting mean residual values.

Second, the use of different sampling techniques results in similar residual values. Despite differences in mean residual values between the *No-peak sampling* and *Peak sampling* methods, residual levels (fitted curve) for coinciding temporal ranges exhibit similar trends. As for the previous case, direct comparison of the techniques using mean residual values is incorrect as differences could be explained by different temporal extends. That is especially relevant as temporal ranges greatly vary between the sampling methods for areas with a high number of SLIPs with uniform age distribution (i.e., MIS assignment). An important observation is that sampling techniques result in different temporal coverage of the residual values. In general, for *No-peak sampling*, the temporal coverage is more extended than the *Peak sampling* due to the higher temporal uncertainty of the SLIPs. Consequently, analysis of the residual with any sampling methods should verify if the assumption that SLIPs are preserved only in highstands (i.e., *Peak sampling*) is applicable. 

The resulting limitations from the proposed methodology indicate required future research needs and open questions. First, further work applying this methodology should expand in statistical techniques that allow comparison between regions by handling differences in the spatial distribution, the number of sea-level indicators by area, age coverage differences, and the proportion of uniform ages (i.e., MIS assigned). A potential path to explore is including the ‘Quality of age’ and ‘Quality of RSL information’ parameter available for the age and RSL parameters to weigh the importance of an individual SLIP in the computation of regional residuals. Similarly, the implementation of a comparison of mean residual values for common age ranges covered by different regions could provide valuable information. Second, as the proposed methodology does not includes limiting data for the analysis, additional work is required to incorporate all sea level indicators (i.e. SLIPs and limiting data) into the analysis. Third, it would require further research to evaluate the extent of residual variability resulting from the method's random sampling techniques. Due to technical limitations and the computational complexity of the methodology, the study only includes a single iteration. Even though similar general conclusions are expected, the variation due to the random component should be studied.

Despite the limitations of the analysis, this work presents an approach to compute residual values by integrating and comparing sea-level change information from multiple origins in a reproducible workflow. This study makes both technical and methodological contributions to the study of sea-level changes. On the one hand, this work presents the implementation of the methods required to compare SLIPs and GIA models, and it handles technical details to facilitate the integration of sea-level information. For example, this work includes new ways to explore the WALIS data set and presents GIA model output [@dendy2017] as an 8-dimensional spatial cube instead of a series of 216 different files contributing to its standardization. As a result, other researchers could apply the method presented in any other region using the code that results from this work. This work tested the proposed method in different geological contexts, explored ways to analyze the resulting residual values, discussed the limitations of the analysis, and proposed potential explanations for different results. An important aspect is that the methodology explores integrating previously excluded data as SLIPs with uniform (MIS Assigned / relative dating) temporal constraints into the statistical methods to analyze sea-level changes. The methodology proposed is built on top of previous efforts to standardize sea-level indicators and shows the potential and methodological and technical challenges to integrate sea-level information from different sources.